name: Update College Football Calendars

on:
  schedule:
    # Run every Tuesday at 8 AM Pacific Time (3 PM UTC)
    - cron: '0 15 * * 2'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-calendars:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Generate calendars
      run: node index.js
      
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/calendars/
        git commit -m "Update college football calendars for next week - $(date +'%Y-%m-%d')"
        git push